//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCosFund
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_salary_statement
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> years { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> pvd_fund_rate { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
